version: "3"

services:
  backend-server:
    environment:
      POSTGRES_HOST: db
      NODE_ENV: production
      PORT:
    env_file:
      - docker.env
    depends_on:
      - db
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: "sasa01/ayoga-backend:latest"
    ports:
      - "8080:8080"
  db:
    image: "postgres:13"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yoga
    ports:
      - "5433:5433"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
