name: backend_cicd

on:
  push:
    branches:
      - "main" #開頭試可以用main,試完ok就轉production
  workflow_dispatch:

env:
  DOCKER_CONTAINER_NAME: sasa01/ayoga-backend:latest
  DOCKER_REPO_NAME: sasa01/ayoga-backend:latest
  SERVER_USER: ubuntu
  SERVER_DIR: /home/ubuntu #一開ubuntu要做野ge path

jobs:
  build-server:
    runs-on: ubuntu-latest
    container: node:lts-alpine
    steps:
      - uses: actions/checkout@v4
      - name: Install yarn deps # name 用來指明這個小步驟在進行什麼
        working-directory: backend #working-directory =要行以下code ge folder 名
        run: | # run 就是在terminal執行下方指令
          yarn
      - name: Build project
        working-directory: backend
        # IN server/package.json => "scripts": { "build": "tsc -p ." }
        run: |
          yarn build
      - name: archive built files
        uses: actions/upload-artifact@v4
        with:
          name: dist #backend build完ge folder名
          path: backend/dist #個build完folder ge path

  deploy-server-to-docker:
    needs: build-server # 代表要完成needs 寫明的 part先進行這一part
    runs-on: ubuntu-latest
    container: docker:20.10.21-alpine3.16
    steps:
      - uses: actions/checkout@v4
      - name: restore built files server
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: backend/dist #提取上一部build左ge dist,所以要同上方path一樣
      - name: Build docker image for server
        working-directory: backend
        run: |
          docker build -t ${{ env.DOCKER_CONTAINER_NAME }} .
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} #secrets ge 要去github-->setting-->secrets and varable-->action種返
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Do Docker tag and push
        working-directory: backend
        run: |
          docker push ${{ env.DOCKER_REPO_NAME }}

  ssh-ec2-and-compose-up:
    needs: deploy-server-to-docker
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} # elastic ip
          key: ${{ secrets.SSH_PRIVATE_KEY }} #  pem檔cat出嚟
          username: ${{ env.SERVER_USER }} #ubuntu  # env. 的東西寫在上方env中
          script: | # script代表逐一執行以下一連串指令
            cd ${{ env.SERVER_DIR }}
            sudo usermod -aG docker ${{ env.SERVER_USER }}
            sudo service docker restart
            sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            sudo docker compose pull 
            sudo docker compose up -d && sudo docker ps
